# services:
#   location-service:
#     build:
#       context: .
#       dockerfile: ./Dockerfile
#     ports:
#       - "3000:3000"
#     env_file:
#       - ./.env
#     networks:
#     - api-network

# networks:
#   api-network:
#     driver: bridge
