# services:
#   payment-service:
#     build:
#       context: .
#       dockerfile: ./Dockerfile
#     ports:
#       - "3001:3001"
#     env_file:
#       - ./.env
#     networks:
#       - api-network

# networks:
#   api-network:
#     driver: bridge